%% Flip Lower Fiber, for Multiplot_2
% necessary for some HIT-SI3 shots (Dual MCIDS till - 1705XXXXX)

function [dat] = flip_lo(dat,flipLoImpact,in,n)

 breakInd = 30; % Assume that the fiber break occurs at index thirty
    impacts=importdata('impacts5.mat')';
    dat(in(n).line).vel(:,breakInd:end) = [dat(in(n).line).vel(:,end:-1:end-2*(length(dat(1).impacts)-flipLoImpact))...
        dat(in(n).line).vel(:,length(dat(1).impacts)-flipLoImpact+breakInd:-1:breakInd) ];
    dat(in(n).line).temp(:,breakInd:end) = [dat(in(n).line).temp(:,end:-1:end-2*(length(dat(1).impacts)-flipLoImpact)) ...
        dat(in(n).line).temp(:,length(dat(1).impacts)-flipLoImpact+breakInd:-1:breakInd) ];
     dat(in(n).line).velU(:,breakInd:end) = [dat(in(n).line).velU(:,end:-1:end-2*(length(dat(1).impacts)-flipLoImpact))...
        dat(in(n).line).velU(:,length(dat(1).impacts)-flipLoImpact+breakInd:-1:breakInd) ];
    dat(in(n).line).tempU(:,breakInd:end) = [dat(in(n).line).tempU(:,end:-1:end-2*(length(dat(1).impacts)-flipLoImpact)) ...
        dat(in(n).line).tempU(:,length(dat(1).impacts)-flipLoImpact+breakInd:-1:breakInd) ];
    dat(in(n).line).velL(:,breakInd:end) = [dat(in(n).line).velL(:,end:-1:end-2*(length(dat(1).impacts)-flipLoImpact))...
        dat(in(n).line).velL(:,length(dat(1).impacts)-flipLoImpact+breakInd:-1:breakInd) ];
    dat(in(n).line).tempL(:,breakInd:end) = [dat(in(n).line).tempL(:,end:-1:end-2*(length(dat(1).impacts)-flipLoImpact)) ...
        dat(in(n).line).tempL(:,length(dat(1).impacts)-flipLoImpact+breakInd:-1:breakInd) ];
    dat(1).impacts(breakInd:end) = [dat(1).impacts(end-2*(length(dat(1).impacts)-flipLoImpact):end);...
        impacts(63:62+(-length(dat(1).impacts)+2*flipLoImpact-breakInd))];
end